name: Deploy Github pages

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install

    - name: Build and deploy
      run: npm run deploy

  merge_to_master:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Merge gh-pages into master
      run: |
        git fetch origin gh-pages:gh-pages
        git checkout master
        git merge gh-pages --no-edit
        git push origin master
